spring:
  application:
    name: tourly-api
  # Database
  datasource:
    url: jdbc:postgresql://tourly-db-tourly.f.aivencloud.com:26657/tourly-db?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  # JPA Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION}

logging:
  level:
    "com.tourly.core": ${LOG_LEVEL:INFO}
    root: ${LOG_LEVEL:INFO}

server:
  # servlet:
  #   context-path: /core/${API_VERSION:v1}  # Commented out for simpler development
  port: ${APP_PORT:8080}
